# Generated by Django 4.2.7 on 2025-07-28 03:09

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='renovacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[core.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXXX-XXXX ou (XX) XXXX-XXXX', regex='^\\(\\d{2}\\)\\s?\\d{4,5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, validators=[core.models.validar_isbn]),
        ),
    ]
