# Generated by Django 4.2.7 on 2025-08-19 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_leitor', '0001_initial'),
        ('app_funcionario', '0001_initial'),
        ('app_livro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('renovacao', models.IntegerField(default=0)),
                ('emprestado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_registrados', to='app_funcionario.funcionario')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_leitor.leitor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_livro.livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
