# Generated by Django 4.2.7 on 2025-08-31 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_emprestimo', '0001_initial'),
        ('app_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='emprestado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_registrados', to='app_funcionario.funcionario'),
        ),
    ]
