# Generated by Django 4.2.7 on 2025-08-31 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_emprestimo', '0002_initial'),
        ('app_livro', '0001_initial'),
        ('app_leitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='leitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_leitor.leitor'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_livro.livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='renovacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovacoes', to='app_emprestimo.emprestimo'),
        ),
    ]
