# Generated by Django 4.2.7 on 2025-08-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appbiblioteca', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('renovacoes', models.IntegerField(default=0)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.funcionario')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leitor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblioteca.livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
